# Copyright (C) 2025
# SPDX-License-Identifier: Apache-2.0

DEVICE_PATH := device/samsung/j7elte

# General Build Flags
ALLOW_MISSING_DEPENDENCIES := true
TARGET_BOARD_PLATFORM := exynos5
TARGET_BOOTLOADER_BOARD_NAME := universal7580
TARGET_NO_BOOTLOADER := true

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := generic
TARGET_USES_64_BIT_BINDER := true

# Kernel
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_KERNEL_SOURCE := kernel/samsung/j7elte
TARGET_KERNEL_CONFIG := j7elte_defconfig
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)

# Prebuilt kernel (optional)
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DT := $(DEVICE_PATH)/prebuilt/dt.img
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DT)
endif

# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 20279584
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 50331648
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor

# Display
TARGET_SCREEN_DENSITY := 480

# Recovery-specific flags
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
RECOVERY_RAMDISK_COMPRESSOR := lzma
BOARD_HAS_LARGE_FILESYSTEM := true

# OrangeFox Tweaks (minimal config)
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_USE_TOOLBOX := false
TW_USE_BUSYBOX := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 50

# Disable extras to save space
TW_INCLUDE_NANO := false
TW_INCLUDE_BASH := false
TW_INCLUDE_LPTOOLS := false
TW_INCLUDE_FB2PNG := false
TW_INCLUDE_RESETPROP := false
TW_INCLUDE_LIBRESETPROP := false
TW_INCLUDE_PYTHON := false
TW_INCLUDE_APP_MANAGER := false
TW_INCLUDE_MAGISK := false
OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
OF_DISABLE_APP_MANAGER := 1
OF_USE_MAGISKBOOT := 1
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_USE_GREEN_LED := 0
OF_UNITY := 1

# Security
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 16.1.0

# APEX
OVERRIDE_TARGET_FLATTEN_APEX := true
